file1 = open("sample1.txt")
file2 = open("sample2.txt")
print("Orinally: ")
data_a= file1.read()
data_b=file2.read()
print("File1: ",data_a)
print("File2: ",data_b)
file1.close()
file2.close()
def swapData():
    file1 = open("sample1.txt", 'w')
    file1.write(data_b)
    file1.close()
    file2 = open("sample2.txt", 'w')
    file2.write(data_a)
    file2.close()

swapData()
file1 = open("sample1.txt")
file2 = open("sample2.txt")
print("Results: ")
print("File1: ",file1.read())
print("File2: ",file2.read())